### ISSUE TITLE
Favicon not visible in dark mode

### ISSUE THREAD

**Issue by angristan** [jhaemin/jhaemin.com-vue#1]
I randomly ended on your github and your website, it's really great!

As explained in that commit comment, I noticed your favicon logo is too dark to be visible under dark mode:

<img width="416" alt="screenshot_2020-07-12_11-51-15@2x" src="https://user-images.githubusercontent.com/11699655/87243728-a2659380-c438-11ea-9671-bd84c2698dca.png">

<img width="424" alt="screenshot_2020-07-12_11-51-06@2x" src="https://user-images.githubusercontent.com/11699655/87243727-a1ccfd00-c438-11ea-8be7-c9820c275752.png">

Cheers!

**Comment by jhaemin** [comment]
https://github.com/jhaemin/jhaemin.com-next/issues/1
